name = "tp-pc-builder-api"
main = "worker.js"
compatibility_date = "2024-11-01"

[vars]
EDIT_PASSWORD = "namhbcf12"

[[d1_databases]]
binding = "DB"
database_name = "tp_pc_builder"
database_id = "da7a92d9-5b3a-4536-8346-b1ee58544744"
